# Generated by Django 5.1.6 on 2025-03-09 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
    ]
