# Generated by Django 5.1.6 on 2025-04-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
