# Generated by Django 5.1.6 on 2025-06-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='iva',
            field=models.BooleanField(default=True),
        ),
    ]
