# Generated by Django 5.0.6 on 2024-07-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_customer_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
