# Generated by Django 5.0.6 on 2024-07-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_category_description_alter_category_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='status',
            field=models.CharField(default='draft', max_length=64),
        ),
    ]
