# Generated by Django 5.0.6 on 2024-08-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_saleorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='status',
            field=models.IntegerField(choices=[(1, 'Borrador'), (2, 'Publicada'), (3, 'Eliminada')], default=1),
        ),
    ]
