# Generated by Django 5.0.6 on 2024-08-09 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_saleorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.customer'),
        ),
    ]
