# Generated by Django 5.0.6 on 2024-08-11 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_product_stock_productstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstock',
            name='buy_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productstock',
            name='sell_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productstock',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.vendor'),
        ),
    ]
