# Generated by Django 5.0.6 on 2024-08-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_productstock_buy_price_productstock_sell_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='buy_price',
            field=models.IntegerField(default=0),
        ),
    ]
