# Generated by Django 5.0.6 on 2024-08-12 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_salereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='salereport',
            name='type',
            field=models.IntegerField(choices=[(1, 'Diario'), (2, 'Semanal'), (3, 'Mensual')], default=None, null=True),
        ),
    ]
