# Generated by Django 5.0.6 on 2024-08-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_salereport_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
