# Generated by Django 5.0.6 on 2024-08-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_saleorder_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salereport',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
