# Generated by Django 5.0.6 on 2025-01-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_debt_date_alter_productstock_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bar_code',
            field=models.IntegerField(default=0),
        ),
    ]
