# Generated by Django 5.0.6 on 2025-01-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_product_bar_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bar_code',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
