# Generated by Django 5.0.6 on 2025-01-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstock',
            name='sell_price',
        ),
        migrations.RemoveField(
            model_name='productstock',
            name='vendor',
        ),
        migrations.AlterField(
            model_name='productstock',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
