# Generated by Django 5.0.6 on 2025-01-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_remove_productstock_sell_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sell_price',
            field=models.FloatField(default=0.0),
        ),
    ]
