# Generated by Django 5.1.6 on 2025-02-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('numberPhone', models.IntegerField(default=None, null=True)),
                ('description', models.TextField(default=None, null=True)),
            ],
        ),
    ]
