# Generated by Django 5.1.6 on 2025-03-11 03:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productstock',
            old_name='buy_price',
            new_name='stock',
        ),
        migrations.RemoveField(
            model_name='productstock',
            name='date',
        ),
        migrations.RemoveField(
            model_name='productstock',
            name='quantity',
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('buy_price', models.IntegerField(default=0)),
                ('product_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.productstock')),
            ],
        ),
    ]
