# Generated by Django 5.1.6 on 2025-04-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_rename_buy_price_productstock_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='voided',
            field=models.BooleanField(default=False),
        ),
    ]
