# Generated by Django 5.1.6 on 2025-06-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stockitem_voided'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='quantity_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
