# Generated by Django 5.1.6 on 2025-06-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_stockitem_quantity_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='is_depleted',
            field=models.BooleanField(default=False),
        ),
    ]
